# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig()

config.source('./themes/default/base16-gruvbox-dark-hard.config.py')

# Downloads
c.downloads.location.directory = '~/Downloads/'
c.downloads.location.prompt = False
c.downloads.remove_finished = 1_000

c.statusbar.show = 'always'
c.statusbar.widgets = ['keypress', 'search_match', 'url', 'scroll', 'history', 'tabs', 'progress']

c.window.transparent = True

c.content.geolocation = False
