# wallpaper
# exec waypaper --restore

exec wl-paste --type text --watch cliphist store # clipboard store text data
exec wl-paste --type image --watch cliphist store # clipboard store image data


# exec mako
# exec swaycons
# turn on bluetooth ctl
# exec bluetoothctl power on
# enable autotiling
exec autotiling
exec wlsunset -l 53.6 -L 9.9 -t 4000 -T 6400
# exec nm-applet --indicator
# startup apps
# exec blueman-applet
#
# lxqt-policykit. Required for higher privilieges
exec /usr/libexec/lxqt-policykit-agent

# Needed for pipewire WebRTC screen sharing already set in /etc/ include
# exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# Swayr daemon
exec env RUST_BACKTRACE=1 RUST_LOG=swayr=debug swayrd > /tmp/swayrd.log 2>&1

# Idle and lock configuration
#
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 60 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
# The timeouts can be customized via `$lock_timeout` and `$screen_timeout`
# variables. For a predictable behavior, keep the `$screen_timeout` value
# lesser than the `$lock_timeout`.
#
# You can also lock the screen manually by running `loginctl lock-session` or
# add a binding for the command. Example:
#     bindsym $mod+Shift+Escape  exec loginctl lock-session
#
# Note that all swaylock customizations are handled via /etc/swaylock/config and
# can be overridden via $XDG_CONFIG_HOME/swaylock/config (~/.config/swaylock/config).
#
exec LT="$lock_timeout" ST="$screen_timeout" LT=${LT:-300} ST=${ST:-60} && \
    swayidle -w \
        timeout $LT 'swaylock -f' \
        timeout $((LT + ST)) 'swaymsg "output * power off"' \
                      resume 'swaymsg "output * power on"'  \
        timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
             resume 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power on"'  \
        before-sleep 'swaylock -f' \
        lock 'swaylock -f' \
        unlock 'pkill -xu "$USER" -SIGUSR1 swaylock'

# GTK3 theme
# set $gnome-schema org.gnome.desktop.interface
#
# exec_always {
#     gsettings set $gnome-schema gtk-theme 'Arc-Gruvbox'
#     gsettings set $gnome-schema icon-theme 'Papirus-Dark'
#     gsettings set $gnome-schema cursor-theme 'Adwaita'
#     gsettings set $gnome-schema font-name 'Cantarell Regular'
# }
#

# Wait until a StatusNotifierItem tray implementation is available
# and process XDG autostart entries. See Fedora 95-xdg-desktop-autostart.conf
# for more context
exec /usr/libexec/sway-systemd/wait-sni-ready && \
    systemctl --user start sway-xdg-autostart.target

# 95-xdg-user-dirs.conf Create or update XDG user dir config
exec /usr/bin/xdg-user-dirs-update
